### ISSUE TITLE
answer.json的key和视频演示的不一样。

### ISSUE THREAD

**Issue by 19245222** [huang1332/finetune_dataset_maker#3]
https://www.bilibili.com/video/BV1P24y1L7Ge/?vd_source=663e83d017ce814585a771e39a20bc82
视频的key是 instruction, input, output. 目前的是 prompt, completion. 很迷惑。
这是视频里的。
![image](https://user-images.githubusercontent.com/110375103/230812219-61b572e5-3ddf-49f9-92bb-eb0931dabb22.png)
这是目前的。
![image](https://user-images.githubusercontent.com/110375103/230812283-7e78636f-eda5-4568-9839-a4dc6fa6f76a.png)

**Comment by littlestone0806** [comment]
> https://www.bilibili.com/video/BV1P24y1L7Ge/?vd_source=663e83d017ce814585a771e39a20bc82 视频的key是 instruction, input, output. 目前的是 prompt, completion. 很迷惑。 这是视频里的。 ![image](https://user-images.githubusercontent.com/110375103/230812219-61b572e5-3ddf-49f9-92bb-eb0931dabb22.png) 这是目前的。 ![image](https://user-images.githubusercontent.com/110375103/230812283-7e78636f-eda5-4568-9839-a4dc6fa6f76a.png)

视频原作者来回复一下。我在作者代码的大概74行，有一处if 0，改为了if 1，因为作者的数据集制作软件，兼容不同的微调模型，默认的是prompt和completion

**Comment by 19245222** [comment]
好的。

>
